-- =========================================================================
-- Generated Snowflake SQL for DEV environment
-- =========================================================================
-- Generated on: 2025-06-25 22:09:13 UTC
-- Environment: dev
-- Database: ECOMMERCE_DB
-- Warehouse: INT_WH
-- S3 Bucket: my-amazing-app
-- =========================================================================
-- 
-- ⚠️  DO NOT EDIT THIS FILE DIRECTLY!
-- This file is automatically generated from templates.
-- Edit the template files in the snowflake/ directory instead.
-- =========================================================================

-- Snowflake File Formats for Parquet Data
-- This script creates reusable file formats for different data types

USE DATABASE ECOMMERCE_DB;
USE SCHEMA BRONZE_LAYER;

-- Standard Parquet format with Snappy compression
CREATE FILE FORMAT IF NOT EXISTS parquet_format
  TYPE = 'PARQUET'
  COMPRESSION = 'SNAPPY'
  COMMENT = 'Standard Parquet format with Snappy compression for pipeline data';

-- Alternative Parquet format with different settings (if needed)
CREATE FILE FORMAT IF NOT EXISTS parquet_format_uncompressed
  TYPE = 'PARQUET'
  COMPRESSION = 'NONE'
  COMMENT = 'Uncompressed Parquet format for debugging';

-- Show created file formats
SHOW FILE FORMATS; 