-- =========================================================================
-- Generated Snowflake SQL for DEV environment
-- =========================================================================
-- Generated on: 2025-06-25 21:32:22 UTC
-- Environment: dev
-- Database: ECOMMERCE_DB
-- Warehouse: INT_WH
-- S3 Bucket: my-amazing-app
-- =========================================================================
-- 
-- ⚠️  DO NOT EDIT THIS FILE DIRECTLY!
-- This file is automatically generated from templates.
-- Edit the template files in the snowflake/ directory instead.
-- =========================================================================

-- =========================================================================
-- Bronze Layer: External Tables (Raw Data from S3)
-- =========================================================================
-- This script creates external tables that directly read from S3 Parquet files
-- These tables form the Bronze layer of the medallion architecture

-- -------------------------------------------------------------------------
-- Bronze Table 1: Raw Users Data
-- -------------------------------------------------------------------------
CREATE EXTERNAL TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.ext_raw_users (
    id STRING AS (value:id::STRING),
    first_name STRING AS (value:first_name::STRING),
    last_name STRING AS (value:last_name::STRING),
    gender STRING AS (value:gender::STRING),
    address STRING AS (value:address::STRING),
    post_code STRING AS (value:post_code::STRING),
    email STRING AS (value:email::STRING),
    username STRING AS (value:username::STRING),
    dob STRING AS (value:dob::STRING),
    registered_date STRING AS (value:registered_date::STRING),
    phone STRING AS (value:phone::STRING),
    picture STRING AS (value:picture::STRING)
)
LOCATION = @ECOMMERCE_DB.BRONZE_LAYER.raw_users_stage/users/raw/parquet/
FILE_FORMAT = (TYPE = PARQUET)
AUTO_REFRESH = TRUE;

-- -------------------------------------------------------------------------
-- Bronze Table 2: User Analytics Data
-- -------------------------------------------------------------------------
CREATE EXTERNAL TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.ext_user_analytics (
    gender STRING AS (value:gender::STRING),
    count NUMBER AS (value:count::NUMBER),
    percentage NUMBER AS (value:percentage::NUMBER),
    email_domain STRING AS (value:email_domain::STRING),
    domain_count NUMBER AS (value:domain_count::NUMBER),
    domain_percentage NUMBER AS (value:domain_percentage::NUMBER),
    processing_timestamp TIMESTAMP AS (value:processing_timestamp::TIMESTAMP)
)
LOCATION = @ECOMMERCE_DB.BRONZE_LAYER.user_analytics_stage/users/analytics/parquet/
FILE_FORMAT = (TYPE = PARQUET)
AUTO_REFRESH = TRUE;

-- -------------------------------------------------------------------------
-- Bronze Table 3: User Demographics Data
-- -------------------------------------------------------------------------
CREATE EXTERNAL TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE_LAYER.ext_user_demographics (
    country STRING AS (value:country::STRING),
    state STRING AS (value:state::STRING),
    user_count NUMBER AS (value:user_count::NUMBER),
    avg_age NUMBER AS (value:avg_age::NUMBER),
    male_percentage NUMBER AS (value:male_percentage::NUMBER),
    female_percentage NUMBER AS (value:female_percentage::NUMBER),
    processing_timestamp TIMESTAMP AS (value:processing_timestamp::TIMESTAMP)
)
LOCATION = @ECOMMERCE_DB.BRONZE_LAYER.user_demographics_stage/users/demographics/parquet/
FILE_FORMAT = (TYPE = PARQUET)
AUTO_REFRESH = TRUE;

-- Examine created external tables
SHOW EXTERNAL TABLES;
DESCRIBE TABLE ECOMMERCE_DB.BRONZE_LAYER.ext_raw_users;
DESCRIBE TABLE ECOMMERCE_DB.BRONZE_LAYER.ext_user_analytics;
DESCRIBE TABLE ECOMMERCE_DB.BRONZE_LAYER.ext_user_demographics; 