default:
  outputs:
    dev:
      type: redshift
      host: [your_redshift_host] # e.g. aaaaaa.us-east-1.redshift.amazonaws.com
      user: [your_redshift_user]
      pass: [your_redshift_password]
      port: 5439
      dbname: [your_redshift_database]
      schema: [your_redshift_schema]
      threads: 4
      sslmode: 'prefer' # or 'require'
  target: dev 